/*
# SalaamCircle — Seed Reference Data

## What this migration does
Populates the database with initial reference/sample content so the app is
fully functional on first launch. All inserts use ON CONFLICT DO NOTHING so
re-running is safe.

## Data seeded
1. Communities (11) — the default category-based community groups
2. Mosques (12) — major UK mosques as verified directory entries
3. News (6) — published news articles with Pexels stock images
4. Jobs (5) — sample job listings (all approved)
5. Events (5) — sample upcoming events (all approved)
6. News articles (3) — pending items in the admin moderation queue

## Important notes
- Community slugs are auto-generated by the trg_generate_community_slug trigger
  during INSERT, so they're not specified manually here.
- Job posted_by is left NULL (no user account exists yet at seed time).
- Event creator_id is left NULL for the same reason.
- All image URLs use Pexels stock photos (per project convention).
*/

-- ============================================================
-- 1. COMMUNITIES (11 default categories)
-- ============================================================
INSERT INTO communities (name, description, category, member_count, is_public) VALUES
  ('Students', 'Muslim students across the UK — university life, accommodation, study tips, and campus resources.', 'students', 0, true),
  ('Business & Entrepreneurship', 'Muslim entrepreneurs, freelancers, and professionals sharing opportunities and advice.', 'business', 0, true),
  ('Marriage & Family', 'Respectful discussions around marriage, family life, and building strong Muslim households.', 'marriage', 0, true),
  ('New Muslims & Reverts', 'A welcoming space for those who have recently embraced Islam — guidance, support, and friendship.', 'reverts', 0, true),
  ('Technology & Innovation', 'Muslim professionals in tech, AI, engineering, and digital industries.', 'technology', 0, true),
  ('Parenting & Children', 'Support and advice for Muslim parents raising children in the UK.', 'parenting', 0, true),
  ('Islamic Studies', 'Deepen your knowledge — Quran, Hadith, Fiqh, and Islamic scholarship.', 'islamic_studies', 0, true),
  ('Brothers', 'A dedicated space for Muslim men — brotherhood, support, and community.', 'brothers', 0, true),
  ('Sisters', 'A dedicated space for Muslim women — sisterhood, empowerment, and community.', 'sisters', 0, true),
  ('Youth', 'For young Muslims navigating identity, education, and life in the UK.', 'youth', 0, true),
  ('Professionals', 'Muslim professionals across all industries — networking, career advice, and mentorship.', 'professionals', 0, true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- 2. MOSQUES (12 major UK mosques)
-- ============================================================
INSERT INTO mosques (name, address, city, region, postcode, is_verified) VALUES
  ('East London Mosque', '82-92 Whitechapel Rd', 'London', 'London', 'E1 1JQ', true),
  ('Birmingham Central Mosque', '180 Belgrave Middleway', 'Birmingham', 'West Midlands', 'B12 0XS', true),
  ('Manchester Central Mosque', 'Upper Park Rd', 'Manchester', 'North West', 'M14 5RU', true),
  ('Leeds Grand Mosque', 'Woodsley Rd', 'Leeds', 'Yorkshire and The Humber', 'LS3 1DL', true),
  ('Bristol Jamia Mosque', 'Green Street', 'Bristol', 'South West', 'BS3 4UB', true),
  ('Glasgow Central Mosque', '1 Mosque Avenue', 'Glasgow', 'Scotland', 'G5 9TA', true),
  ('Cardiff Bay Mosque', 'Loudoun Square', 'Cardiff', 'Wales', 'CF10 5JB', true),
  ('Sheffield Islamic Centre', '49 Wolseley Rd', 'Sheffield', 'Yorkshire and The Humber', 'S8 0ZS', true),
  ('Leicester Central Mosque', 'Conduit St', 'Leicester', 'East Midlands', 'LE2 0JN', true),
  ('Northampton Jamia Mosque', 'St Edmunds Rd', 'Northampton', 'East Midlands', 'NN1 5DY', true),
  ('Bradford Grand Mosque', 'Westgate', 'Bradford', 'Yorkshire and The Humber', 'BD1 2QB', true),
  ('Coventry Jamia Mosque', 'Eagle Street', 'Coventry', 'West Midlands', 'CV1 4GS', true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- 3. NEWS (6 published articles)
-- ============================================================
INSERT INTO news (title, excerpt, content, category, is_featured, image_url) VALUES
  ('UK Muslims celebrate Eid across the country', 'Millions of Muslims across the United Kingdom celebrated Eid with prayers, community gatherings, and festivities in cities and towns.', 'Millions of Muslims across the United Kingdom celebrated Eid with prayers, community gatherings, and festivities in cities and towns. From London to Glasgow, mosques were filled with worshippers attending special Eid prayers, followed by family gatherings, community meals, and charity events.', 'uk', true, 'https://images.pexels.com/photos/3279132/pexels-photo-3279132.jpeg?auto=compress&cs=tinysrgb&w=800'),
  ('New Islamic Centre opens in Birmingham city centre', 'A new purpose-built Islamic Centre has opened its doors in Birmingham, providing prayer facilities and educational programmes.', 'A new purpose-built Islamic Centre has opened its doors in Birmingham, providing prayer facilities and educational programmes for the local community. The centre features a main prayer hall, classrooms, and community spaces.', 'local', false, 'https://images.pexels.com/photos/3886488/pexels-photo-3886488.jpeg?auto=compress&cs=tinysrgb&w=800'),
  ('Ramadan 2026: Community iftar guide across the UK', 'Communities across the UK are hosting a variety of iftar events this Ramadan. From free community iftars at mosques to charity fundraising dinners.', 'Communities across the UK are hosting a variety of iftar events this Ramadan. From free community iftars at mosques to charity fundraising dinners, there are opportunities for everyone to participate in the blessed month.', 'community', false, 'https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=800'),
  ('Muslim charity raises £2m for global humanitarian relief', 'A UK-based Muslim charity has announced a record-breaking fundraising campaign, raising over £2 million for communities affected by humanitarian crises.', 'A UK-based Muslim charity has announced a record-breaking fundraising campaign, raising over £2 million for communities affected by humanitarian crises worldwide. The funds will support emergency relief, food programmes, and long-term development projects.', 'uk', true, 'https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=800'),
  ('Islamic finance sector continues to grow in the UK', 'The Islamic finance sector continues to expand with new halal mortgage products and shariah-compliant savings accounts being launched by major UK banks.', 'The Islamic finance sector continues to expand with new halal mortgage products and shariah-compliant savings accounts being launched by major UK banks. The sector has seen sustained growth as demand for ethical, faith-based financial products increases.', 'uk', false, 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=800'),
  ('Youth Islamic education programme launches nationwide', 'A new nationwide Islamic education programme targeting young Muslims aged 11-18 has launched across 50 UK cities, offering weekend classes and mentorship.', 'A new nationwide Islamic education programme targeting young Muslims aged 11-18 has launched across 50 UK cities, offering weekend classes and mentorship. The programme aims to provide accessible Islamic education alongside academic support.', 'community', false, 'https://images.pexels.com/photos/5212345/pexels-photo-5212345.jpeg?auto=compress&cs=tinysrgb&w=800')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 4. JOBS (5 sample listings, all approved)
-- ============================================================
INSERT INTO jobs (title, employer, location, city, region, description, category, job_type, salary_range, is_featured, is_approved, status)
VALUES
  ('Full Stack Developer', 'Halal Tech Ltd', 'London (Hybrid)', 'London', 'London', 'Full stack developer for ethical fintech products. Node.js, React, PostgreSQL required.', 'technology', 'full_time', '£55,000 – £70,000', true, true, 'approved'),
  ('Islamic Studies Teacher', 'Al-Noor Academy', 'Birmingham', 'Birmingham', 'West Midlands', 'Islamic Studies teacher for secondary school. QTS preferred.', 'education', 'full_time', '£28,000 – £38,000', false, true, 'approved'),
  ('Finance Manager', 'Amanah Finance', 'Manchester', 'Manchester', 'North West', 'ACCA/CIMA qualified finance manager for Islamic finance products and compliance.', 'finance', 'full_time', '£45,000 – £55,000', true, true, 'approved'),
  ('Community Fundraiser', 'Muslim Hands UK', 'Nottingham', 'Nottingham', 'East Midlands', 'Fundraiser to grow our donor community and run local charity events.', 'charity', 'full_time', '£24,000 – £28,000', false, true, 'approved'),
  ('UX Designer', 'Crescent Digital', 'Remote', NULL, NULL, 'UX Designer for our Muslim lifestyle app. Fully remote.', 'technology', 'remote', '£40,000 – £50,000', false, true, 'approved')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 5. EVENTS (5 sample upcoming events, all approved)
-- ============================================================
INSERT INTO events (title, description, category, venue_name, city, region, start_datetime, end_datetime, is_online, is_featured, is_approved, status)
VALUES
  ('Manchester Muslim Professionals Networking', 'Monthly networking for Muslim professionals. Connect, collaborate, and grow over light refreshments.', 'networking', 'Manchester Conference Centre', 'Manchester', 'North West', now() + interval '5 days', now() + interval '5 days' + interval '3 hours', false, true, true, 'approved'),
  ('Quran Memorisation Workshop', 'One-day intensive Tajweed and Hifz workshop for adults and teens. All levels welcome.', 'religious', 'East London Mosque', 'London', 'London', now() + interval '8 days', now() + interval '8 days' + interval '6 hours', false, false, true, 'approved'),
  ('Muslim Entrepreneurs Summit 2026', 'Annual summit for Muslim business owners, investors, and founders.', 'conference', 'Birmingham ICC', 'Birmingham', 'West Midlands', now() + interval '14 days', now() + interval '15 days', false, true, true, 'approved'),
  ('Online Arabic for Beginners', 'Free 6-week online course. Live sessions every Saturday morning.', 'education', 'Online', NULL, NULL, now() + interval '3 days', now() + interval '3 days' + interval '2 hours', true, false, true, 'approved'),
  ('Sisters Halaqa & Wellbeing Morning', 'Monthly halaqa and wellbeing activities for sisters. Light breakfast provided.', 'social', 'Leeds Grand Mosque', 'Leeds', 'Yorkshire and The Humber', now() + interval '10 days', now() + interval '10 days' + interval '3 hours', false, false, true, 'approved')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 6. NEWS ARTICLES (3 pending in admin moderation queue)
-- ============================================================
INSERT INTO news_articles (title, summary, source_name, source_url, status)
VALUES
  ('UK Muslim Council Calls for Greater Community Investment', 'The Muslim Council of Britain has issued a statement calling for increased government investment in Muslim communities across the UK.', 'MCB News', 'https://mcb.org.uk', 'pending'),
  ('New Halal Certification Standards Announced for 2026', 'UK food standards authority outlines updated halal certification requirements taking effect next year.', 'HFA UK', 'https://hfa.org.uk', 'pending'),
  ('Birmingham Islamic Centre Wins Architecture Award', 'The newly opened Birmingham Islamic Centre has been recognised for its innovative design blending modern and traditional Islamic architecture.', 'Architecture Today', 'https://architecturetoday.co.uk', 'pending')
ON CONFLICT DO NOTHING;
