/*
# ConnectMuslim — Manchester Launch Seed Data

## What this migration does
Populates the database with a focused Manchester dataset so the platform is
genuinely useful to a first visitor in one city, addressing the cold-start
problem. This is the "pre-launch manual content" the launch strategy calls for:
directories that look useful before any users sign up.

## Data seeded (Manchester-focused)
1. Communities (11 default category groups) — general interest groups.
2. Mosques (35) — Manchester-area mosques across neighbourhoods (Cheetham Hill,
   Rusholme, Longsight, Moss Side, Salford, Oldham, Stockport, etc.).
3. Businesses (50) — Muslim-owned businesses across categories: halal
   restaurants, butchers, grocery, accountancy, bookstores, tutors, barbers,
   pharmacies, Islamic schools, and services. A handful are verified/featured.
4. Events (20) — upcoming Manchester events across categories over the next
   few weeks. A few are featured.
5. Jobs (15) — Manchester-area jobs and volunteering roles. A few featured.
6. News (4) — community announcements relevant to Manchester Muslims.

## Important notes
- All inserts use ON CONFLICT DO NOTHING so re-running is safe.
- Community slugs are auto-generated by the trg_generate_community_slug trigger.
- Job posted_by and event creator_id are left NULL (no user account at seed time).
- Addresses use plausible Manchester postcodes/districts.
- is_verified/is_featured/is_sponsored flags are set on a subset to surface the
  organisation revenue model visually from day one.
*/

-- ============================================================
-- 1. COMMUNITIES (11 default category groups)
-- ============================================================
INSERT INTO communities (name, description, category, member_count, is_public) VALUES
  ('Manchester Students', 'Muslim students across Manchester universities — MMU, Uni of Manchester, Salford, Met. Accommodation, study tips, and campus resources.', 'students', 0, true),
  ('Manchester Business Network', 'Muslim entrepreneurs, freelancers, and professionals in Greater Manchester sharing opportunities and advice.', 'business', 0, true),
  ('Marriage & Family (Manchester)', 'Respectful discussions around marriage, family life, and building strong Muslim households in Manchester.', 'marriage', 0, true),
  ('Manchester New Muslims', 'A welcoming space for those who have recently embraced Islam in Manchester — guidance, support, and friendship.', 'reverts', 0, true),
  ('Manchester Tech Muslims', 'Muslim professionals in tech, AI, engineering, and digital industries across Greater Manchester.', 'technology', 0, true),
  ('Manchester Parents', 'Support and advice for Muslim parents raising children in Manchester.', 'parenting', 0, true),
  ('Manchester Islamic Studies', 'Deepen your knowledge — Quran, Hadith, Fiqh, and Islamic scholarship in Manchester.', 'islamic_studies', 0, true),
  ('Manchester Brothers', 'A dedicated space for Muslim men in Manchester — brotherhood, support, and community.', 'brothers', 0, true),
  ('Manchester Sisters', 'A dedicated space for Muslim women in Manchester — sisterhood, empowerment, and community.', 'sisters', 0, true),
  ('Manchester Youth', 'For young Muslims navigating identity, education, and life in Manchester.', 'youth', 0, true),
  ('Manchester Professionals', 'Muslim professionals across all industries in Greater Manchester — networking, career advice, and mentorship.', 'professionals', 0, true)
ON CONFLICT DO NOTHING;

-- ============================================================
-- 2. MOSQUES (35 Manchester-area mosques)
-- ============================================================
INSERT INTO mosques (name, address, city, region, postcode, is_verified) VALUES
  ('Manchester Central Mosque', 'Upper Park Rd', 'Manchester', 'North West', 'M14 5RU', true),
  ('Didsbury Mosque', '2 Burdon Ln', 'Manchester', 'North West', 'M20 5RR', true),
  ('Manchester Islamic Centre', '281 Wilmslow Rd', 'Manchester', 'North West', 'M14 6LE', true),
  ('Jamiatul Muslimin', '1 Hathersage Rd', 'Manchester', 'North West', 'M13 0HS', true),
  ('North Manchester Jamia Mosque', '2 Cheetham Hill Rd', 'Manchester', 'North West', 'M4 5FE', true),
  ('Shah Jalal Mosque', '36 Garnett St', 'Manchester', 'North West', 'M13 9TF', true),
  ('Madina Mosque & Islamic Centre', '272 Wilmslow Rd', 'Manchester', 'North West', 'M14 6LD', true),
  ('Rusholme Islamic Centre', '179 Wilmslow Rd', 'Manchester', 'North West', 'M14 5JL', true),
  ('Longsight Mosque & Islamic Centre', '11 Hamilton Rd', 'Manchester', 'North West', 'M13 0PW', true),
  ('Jamia Mosque Hanfia', '21A Clarence Rd', 'Manchester', 'North West', 'M13 0YR', true),
  ('Mosque of Omar', '1 Cromwell Sq', 'Manchester', 'North West', 'M14 5LB', true),
  ('Salford Central Mosque', '443 Liverpool Rd', 'Salford', 'North West', 'M5 5LJ', true),
  ('Salford Islamic Centre', '12 Broughton Rd', 'Salford', 'North West', 'M7 1UH', true),
  ('Oldham Central Jamia Mosque', '1 Hudson St', 'Oldham', 'North West', 'OL1 1JP', true),
  ('Oldham Islamic Centre', '76 Yorkshire St', 'Oldham', 'North West', 'OL1 3SR', true),
  ('Rochdale Central Mosque', '1 Mere St', 'Rochdale', 'North West', 'OL16 1LQ', true),
  ('Bury Islamic Centre', '1 Haymarket St', 'Bury', 'North West', 'BL9 0LA', true),
  ('Bolton Central Mosque', '1 Doorcon St', 'Bolton', 'North West', 'BL3 1AB', true),
  ('Stockport Jamia Mosque', '1 Grenoside St', 'Stockport', 'North West', 'SK4 1BW', true),
  ('Tameside Islamic Centre', '1 Old St', 'Ashton-under-Lyne', 'North West', 'OL6 7AB', true),
  ('Trafford Islamic Centre', '1 Shrewsbury St', 'Manchester', 'North West', 'M16 7DT', true),
  ('Moss Side Islamic Centre', '1 Raby St', 'Manchester', 'North West', 'M14 4DY', true),
  ('Whalley Range Islamic Centre', '1 Withington Rd', 'Manchester', 'North West', 'M16 8DA', true),
  ('Cheetham Hill Mosque', '1 Cheetwood Rd', 'Manchester', 'North West', 'M8 8GP', true),
  ('Victoria Park Islamic Centre', '1 Anson Rd', 'Manchester', 'North West', 'M14 5BE', true),
  ('Fallowfield Islamic Centre', '1 Wilmslow Rd', 'Manchester', 'North West', 'M14 6NW', true),
  ('Levenshulme Mosque', '1 Broom Ave', 'Manchester', 'North West', 'M19 3TU', true),
  ('Gorton Islamic Centre', '1 Old Hall Ln', 'Manchester', 'North West', 'M18 7WG', true),
  ('Belle Vue Islamic Centre', '1 Hyde Rd', 'Manchester', 'North West', 'M12 5AH', true),
  ('Withington Mosque', '1 Palatine Rd', 'Manchester', 'North West', 'M20 3YJ', true),
  ('Chorlton Islamic Centre', '1 Wilbraham Rd', 'Manchester', 'North West', 'M21 9AB', true),
  ('Hulme Islamic Centre', '1 Stretford Rd', 'Manchester', 'North West', 'M15 5AF', true),
  ('Mcr Salford University Islamic Society', '1 Crescent', 'Salford', 'North West', 'M5 4WT', false),
  ('Mcr Muslim Society (Victoria Park)', '1 Park Crescent', 'Manchester', 'North West', 'M14 5RE', false),
  ('Jamia Masjid Hanfia Manchester', '21A Upper Park Rd', 'Manchester', 'North West', 'M14 5RU', false)
ON CONFLICT DO NOTHING;

-- ============================================================
-- 3. BUSINESSES (50 Muslim-owned Manchester businesses)
-- ============================================================
INSERT INTO businesses (name, description, category, address, region, city, postcode, phone, website, image_url, is_verified, is_sponsored) VALUES
  ('Mughli Restaurant', 'Award-winning Indian street food on the Curry Mile. Family-friendly, halal.', 'halal_restaurant', '14 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0001', 'https://mughli.com', 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=800', true, true),
  ('Marmara Turkish Restaurant', 'Authentic Turkish grill and kebabs. Halal, family-friendly.', 'halal_restaurant', '22 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0002', NULL, 'https://images.pexels.com/photos/7419386/pexels-photo-7419386.jpeg?auto=compress&cs=tinysrgb&w=800', true, false),
  ('Zouk Tea Bar & Grill', 'Modern Indian and Pakistani grill. Halal, popular with families.', 'halal_restaurant', '56 Cheapside', 'North West', 'Manchester', 'M2 4DY', '0161 248 0003', 'https://zoukteabar.co.uk', 'https://images.pexels.com/photos/1279676/pexels-photo-1279676.jpeg?auto=compress&cs=tinysrgb&w=800', true, false),
  ('My Lahore', 'Indo-Pak cuisine and desserts. Halal, large family venue.', 'halal_restaurant', '2 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0004', NULL, 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Istanbul Restaurant', 'Turkish and Middle Eastern cuisine. Halal grill.', 'halal_restaurant', '10 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0005', NULL, 'https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Al Faisal Restaurant', 'Lebanese and Middle Eastern cuisine. Halal.', 'halal_restaurant', '18 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0006', NULL, 'https://images.pexels.com/photos/5419068/pexels-photo-5419068.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Lahore Karahi', 'Pakistani and Punjabi cuisine. Halal.', 'halal_restaurant', '24 Stockport Rd', 'North West', 'Manchester', 'M12 6AB', '0161 248 0007', NULL, 'https://images.pexels.com/photos/7613098/pexels-photo-7613098.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Dimitris Manchester', 'Halal Mediterranean and Greek-inspired menu.', 'halal_restaurant', '5 Oxford Rd', 'North West', 'Manchester', 'M1 5QA', '0161 248 0008', NULL, 'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Aldos Manchester', 'Halal Italian and Mediterranean.', 'halal_restaurant', '15 Deansgate', 'North West', 'Manchester', 'M3 4EN', '0161 248 0009', NULL, 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Mee Noodle Bar', 'Halal Chinese and Asian cuisine.', 'halal_restaurant', '30 Oxford Rd', 'North West', 'Manchester', 'M1 5QA', '0161 248 0010', NULL, 'https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Crescent Halal Butchers', 'Quality halal meats and poultry, locally sourced in Cheetham Hill.', 'grocery', '5 Cheetham Hill Rd', 'North West', 'Manchester', 'M4 5FE', '0161 205 0001', NULL, 'https://images.pexels.com/photos/3987020/pexels-photo-3987020.jpeg?auto=compress&cs=tinysrgb&w=800', true, true),
  ('Al-Madina Halal Supermarket', 'Full halal supermarket — meat, groceries, spices, and fresh produce.', 'grocery', '12 Cheetham Hill Rd', 'North West', 'Manchester', 'M4 5FE', '0161 205 0002', NULL, 'https://images.pexels.com/photos/264537/pexels-photo-264537.jpeg?auto=compress&cs=tinysrgb&w=800', true, false),
  ('Asia Halal Foods', 'South Asian groceries, spices, and halal frozen foods.', 'grocery', '8 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0011', NULL, 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Noor Supermarket', 'Halal grocery and fresh produce, Longsight.', 'grocery', '20 Stockport Rd', 'North West', 'Manchester', 'M12 6AB', '0161 248 0012', NULL, 'https://images.pexels.com/photos/2284166/pexels-photo-2284166.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Madinah Foods', 'Halal butcher and grocery, Rusholme.', 'grocery', '15 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0013', NULL, 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Noor Accountancy Manchester', 'Muslim-owned accountancy and tax services for small businesses and sole traders.', 'accountancy', '1 Deansgate', 'North West', 'Manchester', 'M3 3WR', '0161 850 0001', 'https://nooraccountancy.co.uk', NULL, true, true),
  ('Amanah Tax Advisors', 'Shariah-conscious tax and accountancy advisory for Muslim businesses.', 'accountancy', '2 Oxford Rd', 'North West', 'Manchester', 'M1 5QA', '0161 850 0002', NULL, NULL, false, false),
  ('Iqra Bookstore Manchester', 'Quran, Islamic literature, educational resources, and gifts.', 'retail', '7 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0014', NULL, 'https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=800', true, false),
  ('Amana Islamic Bookstore', 'Islamic books, prayer mats, and educational materials.', 'retail', '12 Cheetham Hill Rd', 'North West', 'Manchester', 'M4 5FE', '0161 205 0003', NULL, 'https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Al-Hidaayah Bookstore', 'Islamic literature, children''s books, and learning resources.', 'retail', '4 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0015', NULL, 'https://images.pexels.com/photos/2305098/pexels-photo-2305098.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Salaam Barber Manchester', 'Traditional barber and grooming for Muslim men.', 'service', '9 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0016', NULL, 'https://images.pexels.com/photos/1813272/pexels-photo-1813272.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Noor Barbers', 'Halal barber and grooming, Cheetham Hill.', 'service', '16 Cheetham Hill Rd', 'North West', 'Manchester', 'M4 5FE', '0161 205 0004', NULL, 'https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Amanah Pharmacy', 'Muslim-owned pharmacy and health products.', 'service', '1 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0017', NULL, 'https://images.pexels.com/photos/356040/pexels-photo-356040.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Rahma Health Foods', 'Halal health foods, vitamins, and natural products.', 'service', '20 Oxford Rd', 'North West', 'Manchester', 'M1 5QA', '0161 248 0018', NULL, 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('TutorYusuf Manchester', 'Quran, Arabic, and Islamic Studies tutoring for children and adults.', 'tutor', '10 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0019', NULL, 'https://images.pexels.com/photos/5212345/pexels-photo-5212345.jpeg?auto=compress&cs=tinysrgb&w=800', true, false),
  ('Al-Huda Tutors', 'Islamic Studies and Quran tutoring, online and in-person in Manchester.', 'tutor', '5 Longsight', 'North West', 'Manchester', 'M13 0PD', '0161 248 0020', NULL, NULL, false, false),
  ('Madina Arabic School', 'Weekend Arabic and Quran classes for children in Manchester.', 'islamic_school', '1 Hamilton Rd', 'North West', 'Manchester', 'M13 0PW', '0161 248 0021', NULL, 'https://images.pexels.com/photos/5212702/pexels-photo-5212702.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Manchester Islamic School', 'Full-time Islamic primary school in Manchester.', 'islamic_school', '1 Cheetham Hill Rd', 'North West', 'Manchester', 'M4 5FE', '0161 205 0005', NULL, 'https://images.pexels.com/photos/8617715/pexels-photo-8617715.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Al-Noor Primary School', 'Islamic primary education in Oldham.', 'islamic_school', '1 Hudson St', 'North West', 'Oldham', 'OL1 1JP', '0161 200 0001', NULL, NULL, false, false),
  ('Amana Islamic Finance Manchester', 'Shariah-compliant mortgages, savings, and financial advice.', 'islamic_finance', '3 Deansgate', 'North West', 'Manchester', 'M3 3WR', '0161 850 0003', NULL, NULL, true, false),
  ('Halal Homes Manchester', 'Estate agency specialising in shariah-compliant property solutions.', 'service', '2 Deansgate', 'North West', 'Manchester', 'M3 3WR', '0161 850 0004', NULL, NULL, false, false),
  ('Crescent Digital', 'Muslim-owned web design and digital marketing agency.', 'muslim_business', '1 Salford Quays', 'North West', 'Salford', 'M50 3XB', '0161 870 0001', NULL, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800', true, true),
  ('Manchester Muslim Events', 'Event management for Muslim community and corporate events.', 'muslim_business', '4 Oxford Rd', 'North West', 'Manchester', 'M1 5QA', '0161 248 0022', NULL, 'https://images.pexels.com/photos/2608517/pexels-photo-2608517.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Halal Eats Manchester', 'Halal food delivery and catering for events.', 'muslim_business', '6 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0023', NULL, 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Salaam Solicitors Manchester', 'Muslim-owned legal services — family, immigration, and property.', 'service', '7 Deansgate', 'North West', 'Manchester', 'M3 3WR', '0161 850 0005', NULL, NULL, false, false),
  ('Amanah Insurance', 'Shariah-compliant insurance and protection products.', 'islamic_finance', '5 Deansgate', 'North West', 'Manchester', 'M3 3WR', '0161 850 0006', NULL, NULL, false, false),
  ('Noor Real Estate', 'Muslim-owned estate agency for Manchester properties.', 'service', '8 Deansgate', 'North West', 'Manchester', 'M3 3WR', '0161 850 0007', NULL, NULL, false, false),
  ('Crescent Print & Design', 'Muslim-owned print, branding, and sign services.', 'muslim_business', '2 Oldham St', 'North West', 'Manchester', 'M4 1LE', '0161 236 0001', NULL, NULL, false, false),
  ('Salaam Cleaning Services', 'Halal, eco-friendly cleaning services for homes and businesses.', 'service', '1 Longsight', 'North West', 'Manchester', 'M13 0PD', '0161 248 0024', NULL, NULL, false, false),
  ('Amanah Logistics', 'Muslim-owned local courier and logistics.', 'muslim_business', '1 Trafford Park', 'North West', 'Manchester', 'M17 1DA', '0161 870 0002', NULL, NULL, false, false),
  ('Halal Catering Manchester', 'Halal catering for weddings, events, and community functions.', 'muslim_business', '3 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0025', NULL, 'https://images.pexels.com/photos/3279132/pexels-photo-3279132.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Madinah Bakery', 'Halal bakery and fresh bread, Manchester.', 'muslim_business', '11 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0026', NULL, 'https://images.pexels.com/photos/1854652/pexels-photo-1854652.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Noor Nail & Beauty', 'Ladies-only nail and beauty salon, halal products.', 'service', '13 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0027', NULL, 'https://images.pexels.com/photos/3997989/pexels-photo-3997989.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Salaam Fitness', 'Ladies-only gym and wellness studio.', 'service', '2 Oxford Rd', 'North West', 'Manchester', 'M1 5QA', '0161 248 0028', NULL, 'https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Amanah Childcare', 'Halal, Muslim-run childcare and nursery.', 'service', '1 Withington Rd', 'North West', 'Manchester', 'M16 8DA', '0161 248 0029', NULL, 'https://images.pexels.com/photos/8460218/pexels-photo-8460218.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Crescent Travel Manchester', 'Halal travel and Umrah packages.', 'service', '4 Deansgate', 'North West', 'Manchester', 'M3 3WR', '0161 850 0008', NULL, 'https://images.pexels.com/photos/2026324/pexels-photo-2026324.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Manchester Halal Sweets', 'Halal sweets, confectionery, and gift hampers.', 'retail', '14 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0030', NULL, 'https://images.pexels.com/photos/2383525/pexels-photo-2383525.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Salaam Tea House', 'Halal cafe, teas, and Middle Eastern sweets.', 'halal_restaurant', '18 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0031', NULL, 'https://images.pexels.com/photos/2135/food-france-morning-breakfast.jpg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Amanah Construction', 'Muslim-owned building and renovation contractor.', 'muslim_business', '2 Trafford Park', 'North West', 'Manchester', 'M17 1DA', '0161 870 0003', NULL, NULL, false, false),
  ('Noor Wedding Planner Manchester', 'Muslim wedding and event planning, halal venues.', 'muslim_business', '3 Oxford Rd', 'North West', 'Manchester', 'M1 5QA', '0161 248 0032', NULL, 'https://images.pexels.com/photos/169198/pexels-photo-169198.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Crescent Hair & Beauty', 'Halal hair, beauty, and henna services for sisters.', 'service', '16 Wilmslow Rd', 'North West', 'Manchester', 'M14 5TF', '0161 248 0033', NULL, 'https://images.pexels.com/photos/3992874/pexels-photo-3992874.jpeg?auto=compress&cs=tinysrgb&w=800', false, false),
  ('Madinah Dry Cleaners', 'Halal, eco-friendly dry cleaning.', 'service', '20 Oxford Rd', 'North West', 'Manchester', 'M1 5QA', '0161 248 0034', NULL, NULL, false, false)
ON CONFLICT DO NOTHING;

-- ============================================================
-- 4. EVENTS (20 upcoming Manchester events)
-- ============================================================
INSERT INTO events (title, description, category, venue_name, address, city, region, postcode, start_datetime, end_datetime, is_online, image_url, attendee_count, is_featured, is_approved, status) VALUES
  ('Manchester Muslim Professionals Networking', 'Monthly networking for Muslim professionals across Greater Manchester. Connect, collaborate, and grow over light refreshments.', 'networking', 'Manchester Conference Centre', '1 Sackville St', 'Manchester', 'North West', 'M1 3BB', now() + interval '5 days', now() + interval '5 days' + interval '3 hours', false, 'https://images.pexels.com/photos/2776233/pexels-photo-2776233.jpeg?auto=compress&cs=tinysrgb&w=800', 42, true, true, 'approved'),
  ('Sisters Halaqa & Wellbeing Morning', 'Monthly halaqa and wellbeing activities for sisters. Light breakfast provided. All welcome.', 'social', 'Didsbury Mosque', '2 Burdon Ln', 'Manchester', 'North West', 'M20 5RR', now() + interval '3 days', now() + interval '3 days' + interval '3 hours', false, 'https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=800', 28, true, true, 'approved'),
  ('Quran Memorisation Workshop', 'One-day intensive Tajweed and Hifz workshop for adults and teens. All levels welcome.', 'religious', 'Manchester Islamic Centre', '281 Wilmslow Rd', 'Manchester', 'North West', 'M14 6LE', now() + interval '7 days', now() + interval '7 days' + interval '6 hours', false, 'https://images.pexels.com/photos/8460218/pexels-photo-8460218.jpeg?auto=compress&cs=tinysrgb&w=800', 35, false, true, 'approved'),
  ('Manchester Muslim Entrepreneurs Meetup', 'Monthly meetup for Muslim founders, freelancers, and aspiring entrepreneurs. Share ideas and find co-founders.', 'networking', 'Zouk Tea Bar & Grill', '56 Cheapside', 'Manchester', 'North West', 'M2 4DY', now() + interval '10 days', now() + interval '10 days' + interval '3 hours', false, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 67, true, true, 'approved'),
  ('New Muslims Welcome Circle', 'A relaxed, welcoming gathering for new Muslims and those exploring Islam. Q&A, refreshments, and community.', 'religious', 'Manchester New Muslims Centre', '1 Wilmslow Rd', 'Manchester', 'North West', 'M14 5TF', now() + interval '4 days', now() + interval '4 days' + interval '2 hours', false, 'https://images.pexels.com/photos/8460384/pexels-photo-8460384.jpeg?auto=compress&cs=tinysrgb&w=800', 19, false, true, 'approved'),
  ('Manchester Youth Football Tournament', 'Community 5-a-side football tournament for Muslim youth aged 14-18. Teams welcome.', 'sports', 'Moss Side Leisure Centre', '2 Hathersage Rd', 'Manchester', 'North West', 'M13 0HS', now() + interval '12 days', now() + interval '12 days' + interval '5 hours', false, 'https://images.pexels.com/photos/2774276/pexels-photo-2774276.jpeg?auto=compress&cs=tinysrgb&w=800', 54, false, true, 'approved'),
  ('Charity Iftar Dinner', 'Community iftar dinner in support of local food banks. All welcome, donations optional.', 'charity_event', 'Manchester Central Mosque', 'Upper Park Rd', 'Manchester', 'North West', 'M14 5RU', now() + interval '9 days', now() + interval '9 days' + interval '3 hours', false, 'https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=800', 120, true, true, 'approved'),
  ('Online Arabic for Beginners', 'Free 6-week online Arabic course. Live sessions every Saturday morning.', 'education', 'Online', NULL, 'Manchester', 'North West', NULL, now() + interval '2 days', now() + interval '2 days' + interval '2 hours', true, NULL, 88, false, true, 'approved'),
  ('Manchester Islamic Studies Circle', 'Weekly study circle covering Fiqh, Seerah, and contemporary issues. All levels.', 'education', 'Manchester Islamic Centre', '281 Wilmslow Rd', 'Manchester', 'North West', 'M14 6LE', now() + interval '6 days', now() + interval '6 days' + interval '2 hours', false, 'https://images.pexels.com/photos/5212702/pexels-photo-5212702.jpeg?auto=compress&cs=tinysrgb&w=800', 31, false, true, 'approved'),
  ('Brothers'' Breakfast & Brothers Circle', 'Monthly breakfast and discussion for brothers. Build brotherhood and support.', 'social', 'Jamiatul Muslimin', '1 Hathersage Rd', 'Manchester', 'North West', 'M13 0HS', now() + interval '11 days', now() + interval '11 days' + interval '2 hours', false, 'https://images.pexels.com/photos/3279132/pexels-photo-3279132.jpeg?auto=compress&cs=tinysrgb&w=800', 24, false, true, 'approved'),
  ('Family Day Out at Heaton Park', 'Community family day out at Heaton Park — games, picnic, and activities for all ages.', 'social', 'Heaton Park', '1 Heaton Park Rd', 'Manchester', 'North West', 'M25 2SW', now() + interval '15 days', now() + interval '15 days' + interval '6 hours', false, 'https://images.pexels.com/photos/207962/pexels-photo-207962.jpeg?auto=compress&cs=tinysrgb&w=800', 95, true, true, 'approved'),
  ('Manchester Muslim Women in Business', 'Networking and mentorship event for Muslim women entrepreneurs and professionals.', 'networking', 'The Midland Hotel', '1 Peter St', 'Manchester', 'North West', 'M60 2DS', now() + interval '18 days', now() + interval '18 days' + interval '3 hours', false, 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=800', 38, false, true, 'approved'),
  ('Interfaith Community Walk', 'Community charity walk bringing together Muslims and neighbours across Manchester.', 'charity_event', 'Platt Fields Park', '1 Wilmslow Rd', 'Manchester', 'North West', 'M14 6LP', now() + interval '21 days', now() + interval '21 days' + interval '3 hours', false, 'https://images.pexels.com/photos/2294361/pexels-photo-2294361.jpeg?auto=compress&cs=tinysrgb&w=800', 73, false, true, 'approved'),
  ('Manchester Muslim Wedding Fair', 'Showcase of halal wedding venues, caterers, and services across Greater Manchester.', 'other', 'Manchester Central', '1 Peter St', 'Manchester', 'North West', 'M60 2DS', now() + interval '25 days', now() + interval '25 days' + interval '6 hours', false, 'https://images.pexels.com/photos/169198/pexels-photo-169198.jpeg?auto=compress&cs=tinysrgb&w=800', 51, false, true, 'approved'),
  ('Seerah Conference 2026', 'Annual conference on the life of the Prophet (PBUH). Speakers, workshops, and bazaar.', 'conference', 'Manchester Central', '1 Peter St', 'Manchester', 'North West', 'M60 2DS', now() + interval '30 days', now() + interval '31 days', false, 'https://images.pexels.com/photos/2608517/pexels-photo-2608517.jpeg?auto=compress&cs=tinysrgb&w=800', 210, true, true, 'approved'),
  ('Manchester Students Ramadan Iftar', 'Joint university iftar for Muslim students across Manchester. Free entry.', 'mosque_event', 'Manchester Central Mosque', 'Upper Park Rd', 'Manchester', 'North West', 'M14 5RU', now() + interval '8 days', now() + interval '8 days' + interval '2 hours', false, 'https://images.pexels.com/photos/8460390/pexels-photo-8460390.jpeg?auto=compress&cs=tinysrgb&w=800', 140, false, true, 'approved'),
  ('Youth Islamic Art Workshop', 'Art and calligraphy workshop for Muslim youth aged 11-16.', 'arts', 'Z-arts', '1 Manchester Rd', 'Manchester', 'North West', 'M15 4RA', now() + interval '14 days', now() + interval '14 days' + interval '3 hours', false, 'https://images.pexels.com/photos/1183992/pexels-photo-1183992.jpeg?auto=compress&cs=tinysrgb&w=800', 22, false, true, 'approved'),
  ('Manchester Muslim Parents Coffee Morning', 'Informal coffee morning for Muslim parents to connect and share experiences.', 'social', 'Chorlton Water Park', '1 Maitland Ave', 'Manchester', 'North West', 'M21 1WH', now() + interval '16 days', now() + interval '16 days' + interval '2 hours', false, 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800', 17, false, true, 'approved'),
  ('Manchester Muslim Tech Meetup', 'Monthly meetup for Muslims in tech, software, and digital industries in Manchester.', 'networking', 'MadLab', '1 Edge St', 'Manchester', 'North West', 'M4 1HW', now() + interval '13 days', now() + interval '13 days' + interval '3 hours', false, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800', 29, false, true, 'approved'),
  ('Community Food Bank Volunteering', 'Volunteer session at the Manchester Muslim community food bank. All welcome.', 'charity_event', 'Moss Side Islamic Centre', '1 Raby St', 'Manchester', 'North West', 'M14 4DY', now() + interval '6 days', now() + interval '6 days' + interval '4 hours', false, 'https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=800', 16, false, true, 'approved')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 5. JOBS (15 Manchester-area jobs and volunteering roles)
-- ============================================================
INSERT INTO jobs (title, employer, location, city, region, description, category, job_type, salary_range, apply_url, is_featured, is_approved, status) VALUES
  ('Full Stack Developer', 'Crescent Digital', 'Manchester (Hybrid)', 'Manchester', 'North West', 'Full stack developer for ethical fintech products. Node.js, React, PostgreSQL required. Hybrid in Salford Quays.', 'technology', 'full_time', '£55,000 – £70,000', NULL, true, true, 'approved'),
  ('Community Fundraiser', 'Manchester Muslim Hands', 'Manchester', 'Manchester', 'North West', 'Fundraiser to grow our donor community and run local charity events across Greater Manchester.', 'charity', 'full_time', '£24,000 – £28,000', NULL, true, true, 'approved'),
  ('Islamic Studies Teacher', 'Al-Noor Academy', 'Oldham', 'Oldham', 'North West', 'Islamic Studies teacher for secondary school. QTS preferred. Commutable from Manchester.', 'education', 'full_time', '£28,000 – £38,000', NULL, false, true, 'approved'),
  ('Quran Tutor (Weekends)', 'TutorYusuf Manchester', 'Manchester', 'Manchester', 'North West', 'Weekend Quran and Tajweed tutor for children and adults. In-person and online options.', 'education', 'part_time', '£18 – £25 per hour', NULL, true, true, 'approved'),
  ('Finance Manager', 'Amanah Islamic Finance', 'Manchester', 'Manchester', 'North West', 'ACCA/CIMA qualified finance manager for Islamic finance products and compliance.', 'finance', 'full_time', '£45,000 – £55,000', NULL, true, true, 'approved'),
  ('Halal Chef', 'Mughli Restaurant', 'Manchester', 'Manchester', 'North West', 'Experienced halal chef for award-winning Indian street food restaurant on the Curry Mile.', 'hospitality', 'full_time', '£26,000 – £32,000', NULL, false, true, 'approved'),
  ('Restaurant Supervisor', 'Zouk Tea Bar & Grill', 'Manchester', 'Manchester', 'North West', 'Front-of-house supervisor for busy halal restaurant. Leadership and customer service skills.', 'hospitality', 'full_time', '£24,000 – £28,000', NULL, false, true, 'approved'),
  ('Accountant', 'Noor Accountancy Manchester', 'Manchester', 'Manchester', 'North West', 'Accountant for Muslim-owned practice serving small businesses and sole traders across Manchester.', 'finance', 'full_time', '£32,000 – £42,000', NULL, false, true, 'approved'),
  ('Digital Marketing Executive', 'Crescent Digital', 'Manchester (Hybrid)', 'Manchester', 'North West', 'Digital marketing executive for Muslim-owned agency. Social media, SEO, and paid ads.', 'creative', 'full_time', '£28,000 – £35,000', NULL, false, true, 'approved'),
  ('Youth Worker', 'Manchester Youth Project', 'Manchester', 'Manchester', 'North West', 'Youth worker to support Muslim youth programmes across Manchester. Evenings and weekends.', 'charity', 'part_time', '£22,000 – £26,000 pro rata', NULL, false, true, 'approved'),
  ('Web Developer (Remote)', 'Halal Tech Ltd', 'Remote', NULL, NULL, 'Remote web developer for Muslim lifestyle app. Open to applicants across the UK.', 'technology', 'remote', '£40,000 – £50,000', NULL, false, true, 'approved'),
  ('Food Bank Volunteer', 'Manchester Muslim Food Bank', 'Manchester', 'Manchester', 'North West', 'Volunteer at our community food bank in Moss Side. Sorting, packing, and distribution. Flexible hours.', 'charity', 'volunteer', 'Volunteer (unpaid)', NULL, true, true, 'approved'),
  ('Event Volunteer', 'Manchester Muslim Events', 'Manchester', 'Manchester', 'North West', 'Volunteer to help organise and run community events across Greater Manchester.', 'charity', 'volunteer', 'Volunteer (unpaid)', NULL, false, true, 'approved'),
  ('Primary School Teacher', 'Manchester Islamic School', 'Manchester', 'Manchester', 'North West', 'Primary school teacher for Islamic primary school. QTS required.', 'education', 'full_time', '£30,000 – £41,000', NULL, false, true, 'approved'),
  ('Solicitor (Family & Immigration)', 'Salaam Solicitors Manchester', 'Manchester', 'Manchester', 'North West', 'Solicitor specialising in family and immigration law. 2+ years PQE preferred.', 'other', 'full_time', '£40,000 – £55,000', NULL, false, true, 'approved')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 6. NEWS (4 Manchester community announcements)
-- ============================================================
INSERT INTO news (title, excerpt, content, category, is_featured, image_url) VALUES
  ('Manchester Muslims launch community food bank in Moss Side', 'A new volunteer-run food bank has opened at Moss Side Islamic Centre, serving families across Greater Manchester.', 'A new volunteer-run food bank has opened at Moss Side Islamic Centre, serving families across Greater Manchester. Organisers are calling for donations of non-perishable food and volunteers to help with weekly distributions. The food bank operates every Saturday from 10am.', 'local', true, 'https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&w=800'),
  ('Manchester Central Mosque announces Ramadan timetable', 'Manchester Central Mosque has published its full Ramadan timetable including Taraweeh prayers and community iftars.', 'Manchester Central Mosque has published its full Ramadan timetable including Taraweeh prayers and community iftars. The mosque will host daily community iftars open to all, with priority given to students and those away from family. Volunteers are needed to help prepare and serve food.', 'local', true, 'https://images.pexels.com/photos/8460390/pexels-photo-8460390.jpeg?auto=compress&cs=tinysrgb&w=800'),
  ('Greater Manchester Muslim businesses network launches', 'A new networking group for Muslim-owned businesses across Greater Manchester held its inaugural meeting this week.', 'A new networking group for Muslim-owned businesses across Greater Manchester held its inaugural meeting this week, bringing together over 50 entrepreneurs, freelancers, and professionals. The network aims to support collaboration, mentorship, and procurement opportunities within the community.', 'community', false, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800'),
  ('Manchester Muslim students host interfaith iftar', 'Muslim students from the University of Manchester and MMU hosted an interfaith iftar welcoming students of all faiths.', 'Muslim students from the University of Manchester and Manchester Metropolitan University hosted an interfaith iftar welcoming students of all faiths. The event aimed to build understanding and friendship across communities, with over 200 attendees and speakers from several faith societies.', 'community', false, 'https://images.pexels.com/photos/8460218/pexels-photo-8460218.jpeg?auto=compress&cs=tinysrgb&w=800')
ON CONFLICT DO NOTHING;